
//login
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS"
export const LOGIN_REQUEST_FAIL = "LOGIN_REQUEST_FAIL"

//refresh token
export const REFRESH_TOKEN_REQUEST = "REFRESH_TOKEN_REQUEST"
export const REFRESH_TOKEN_REQUEST_SUCCESS = "REFRESH_TOKEN_REQUEST_SUCCESS"
export const REFRESH_TOKEN_REQUEST_FAIL = "REFRESH_TOKEN_REQUEST_FAIL"

//get user
export const GET_USERS_REQUEST = "GET_USERS_REQUEST"
export const GET_USERS_REQUEST_SUCCESS = "GET_USERS_REQUEST_SUCCESS"
export const GET_USERS_REQUEST_FAIL = "GET_USERS_REQUEST_FAIL"

//add user
export const ADD_USERS_REQUEST = "ADD_USERS_REQUEST"
export const ADD_USERS_REQUEST_SUCCESS = "ADD_USERS_REQUEST_SUCCESS"
export const ADD_USERS_REQUEST_FAIL = "ADD_USERS_REQUEST_FAIL"

//edit user
export const EDIT_USERS_REQUEST = "EDIT_USERS_REQUEST"
export const EDIT_USERS_REQUEST_SUCCESS = "EDIT_USERS_REQUEST_SUCCESS"
export const EDIT_USERS_REQUEST_FAIL = "EDIT_USERS_REQUEST_FAIL"

//change password user
export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST"
export const CHANGE_PASSWORD_REQUEST_SUCCESS = "CHANGE_PASSWORD_REQUEST_SUCCESS"
export const CHANGE_PASSWORD_REQUEST_FAIL = "CHANGE_PASSWORD_REQUEST_FAIL"

//get avatar user
export const GET_AVATAR_REQUEST = "GET_AVATAR_REQUEST"
export const GET_AVATAR_REQUEST_SUCCESS = "GET_AVATAR_REQUEST_SUCCESS"
export const GET_AVATAR_REQUEST_FAIL = "GET_AVATAR_REQUEST_FAIL"

//update avatar user
export const UPDATE_AVATAR_REQUEST = "UPDATE_AVATAR_REQUEST"
export const UPDATE_AVATAR_REQUEST_SUCCESS = "UPDATE_AVATAR_REQUEST_SUCCESS"
export const UPDATE_AVATAR_REQUEST_FAIL = "UPDATE_AVATAR_REQUEST_FAIL"

//get partner
export const GET_PARTNER_REQUEST = "GET_PARTNER_REQUEST"
export const GET_PARTNER_REQUEST_SUCCESS = "GET_PARTNER_REQUEST_SUCCESS"
export const GET_PARTNER_REQUEST_FAIL = "GET_PARTNER_REQUEST_FAIL"

//get avatar partner
export const GET_AVATAR_PARTNER_REQUEST = "GET_AVATAR_PARTNER_REQUEST"
export const GET_AVATAR_PARTNER_REQUEST_SUCCESS = "GET_AVATAR_PARTNER_REQUEST_SUCCESS"
export const GET_AVATAR_PARTNER_REQUEST_FAIL = "GET_AVATAR_PARTNER_REQUEST_FAIL"

//add partner
export const ADD_PARTNER_REQUEST = "ADD_PARTNER_REQUEST"
export const ADD_PARTNER_REQUEST_SUCCESS = "ADD_PARTNER_REQUEST_SUCCESS"
export const ADD_PARTNER_REQUEST_FAIL = "ADD_PARTNER_REQUEST_FAIL"

//update avatar partner
export const UPDATE_AVATAR_PARTNER_REQUEST = "UPDATE_AVATAR_PARTNER_REQUEST"
export const UPDATE_AVATAR_PARTNER_REQUEST_SUCCESS = "UPDATE_AVATAR_PARTNER_REQUEST_SUCCESS"
export const UPDATE_AVATAR_PARTNER_REQUEST_FAIL = "UPDATE_AVATAR_PARTNER_REQUEST_FAIL"

//edit partner
export const EDIT_PARTNER_REQUEST = "EDIT_PARTNER_REQUEST"
export const EDIT_PARTNER_REQUEST_SUCCESS = "EDIT_PARTNER_REQUEST_SUCCESS"
export const EDIT_PARTNER_REQUEST_FAIL = "EDIT_PARTNER_REQUEST_FAIL"

//get date info
export const GET_DATE_REQUEST = "GET_DATE_REQUEST"
export const GET_DATE_REQUEST_SUCCESS = "GET_DATE_REQUEST_SUCCESS"
export const GET_DATE_REQUEST_FAIL = "GET_DATE_REQUEST_FAIL"

//add date info
export const ADD_DATE_REQUEST = "ADD_DATE_REQUEST"
export const ADD_DATE_REQUEST_SUCCESS = "ADD_DATE_REQUEST_SUCCESS"
export const ADD_DATE_REQUEST_FAIL = "ADD_DATE_REQUEST_FAIL"

//edit date info
export const EDIT_DATE_REQUEST = "EDIT_DATE_REQUEST"
export const EDIT_DATE_REQUEST_SUCCESS = "EDIT_DATE_REQUEST_SUCCESS"
export const EDIT_DATE_REQUEST_FAIL = "EDIT_DATE_REQUEST_FAIL"


