
//login
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS"
export const LOGIN_REQUEST_FAIL = "LOGIN_REQUEST_FAIL"

//refresh token
export const REFRESH_TOKEN_REQUEST = "REFRESH_TOKEN_REQUEST"
export const REFRESH_TOKEN_REQUEST_SUCCESS = "REFRESH_TOKEN_REQUEST_SUCCESS"
export const REFRESH_TOKEN_REQUEST_FAIL = "REFRESH_TOKEN_REQUEST_FAIL"

//get user
export const GET_USERS_REQUEST = "GET_USERS_REQUEST"
export const GET_USERS_REQUEST_SUCCESS = "GET_USERS_REQUEST_SUCCESS"
export const GET_USERS_REQUEST_FAIL = "GET_USERS_REQUEST_FAIL"

//add user
export const ADD_USERS_REQUEST = "ADD_USERS_REQUEST"
export const ADD_USERS_REQUEST_SUCCESS = "ADD_USERS_REQUEST_SUCCESS"
export const ADD_USERS_REQUEST_FAIL = "ADD_USERS_REQUEST_FAIL"

//edit username
export const EDIT_USERNAME_REQUEST = "EDIT_USERNAME_REQUEST"
export const EDIT_USERNAME_REQUEST_SUCCESS = "EDIT_USERNAME_REQUEST_SUCCESS"
export const EDIT_USERNAME_REQUEST_FAIL = "EDIT_USERNAME_REQUEST_FAIL"

//edit love day
export const EDIT_LOVEDAY_REQUEST = "EDIT_LOVEDAY_REQUEST"
export const EDIT_LOVEDAY_REQUEST_SUCCESS = "EDIT_LOVEDAY_REQUEST_SUCCESS"
export const EDIT_LOVEDAY_REQUEST_FAIL = "EDIT_LOVEDAY_REQUEST_FAIL"

//edit love day
export const EDIT_BIRTHDAY_REQUEST = "EDIT_BIRTHDAY_REQUEST"
export const EDIT_BIRTHDAY_REQUEST_SUCCESS = "EDIT_BIRTHDAY_REQUEST_SUCCESS"
export const EDIT_BIRTHDAY_REQUEST_FAIL = "EDIT_BIRTHDAY_REQUEST_FAIL"

//change password user
export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST"
export const CHANGE_PASSWORD_REQUEST_SUCCESS = "CHANGE_PASSWORD_REQUEST_SUCCESS"
export const CHANGE_PASSWORD_REQUEST_FAIL = "CHANGE_PASSWORD_REQUEST_FAIL"

//get avatar user
export const GET_AVATAR_REQUEST = "GET_AVATAR_REQUEST"
export const GET_AVATAR_REQUEST_SUCCESS = "GET_AVATAR_REQUEST_SUCCESS"
export const GET_AVATAR_REQUEST_FAIL = "GET_AVATAR_REQUEST_FAIL"

//update avatar user
export const UPDATE_AVATAR_REQUEST = "UPDATE_AVATAR_REQUEST"
export const UPDATE_AVATAR_REQUEST_SUCCESS = "UPDATE_AVATAR_REQUEST_SUCCESS"
export const UPDATE_AVATAR_REQUEST_FAIL = "UPDATE_AVATAR_REQUEST_FAIL"

//get list notes
export const GET_LIST_NOTE_REQUEST = "GET_LIST_NOTE_REQUEST"
export const GET_LIST_NOTE_SUCCESS = "GET_LIST_NOTE_SUCCESS"
export const GET_LIST_NOTE_FAIL = "GET_LIST_NOTE_FAIL"

//get list notes
export const GET_MORE_NOTE_REQUEST = "GET_MORE_NOTE_REQUEST"
export const GET_MORE_NOTE_SUCCESS = "GET_MORE_NOTE_SUCCESS"
export const GET_MORE_NOTE_FAIL = "GET_MORE_NOTE_FAIL"

//get add notes
export const ADD_NOTE_REQUEST = "ADD_NOTE_REQUEST"
export const ADD_NOTE_SUCCESS = "ADD_NOTE_SUCCESS"
export const ADD_NOTE_FAIL = "ADD_NOTE_FAIL"

//get note info
export const GET_NOTE_INFO_REQUEST = "GET_NOTE_INFO_REQUEST"
export const GET_NOTE_INFO_SUCCESS = "GET_NOTE_INFO_SUCCESS"
export const GET_NOTE_INFO_FAIL = "GET_NOTE_INFO_FAIL"

//get note images
export const GET_NOTE_IMAGES_REQUEST = "GET_NOTE_IMAGES_REQUEST"
export const GET_NOTE_IMAGES_SUCCESS = "GET_NOTE_IMAGES_SUCCESS"
export const GET_NOTE_IMAGES_FAIL = "GET_NOTE_IMAGES_FAIL"

//get delete notes
export const DELETE_NOTE_REQUEST = "DELETE_NOTE_REQUEST"
export const DELETE_NOTE_SUCCESS = "DELETE_NOTE_SUCCESS"
export const DELETE_NOTE_FAIL = "DELETE_NOTE_FAIL"

//get notes on this day
export const ON_THIS_DAY_REQUEST = "ON_THIS_DAY_REQUEST"
export const ON_THIS_DAY_SUCCESS = "ON_THIS_DAY_SUCCESS"
export const ON_THIS_DAY_FAIL = "ON_THIS_DAY_FAIL"

//get notes by week
export const BY_WEEK_REQUEST = "BY_WEEK_REQUEST"
export const BY_WEEK_SUCCESS = "BY_WEEK_SUCCESS"
export const BY_WEEK_FAIL = "BY_WEEK_FAIL"

//get name partner
export const GET_NAME_PARTNER_REQUEST = "GET_NAME_PARTNER_REQUEST"
export const GET_NAME_PARTNER_SUCCESS = "GET_NAME_PARTNER_SUCCESS"
export const GET_NAME_PARTNER_FAIL = "GET_NAME_PARTNER_FAIL"

//get avatar partner
export const GET_AVATAR_PARTNER_REQUEST = "GET_AVATAR_PARTNER_REQUEST"
export const GET_AVATAR_PARTNER_SUCCESS = "GET_AVATAR_PARTNER_SUCCESS"
export const GET_AVATAR_PARTNER_FAIL = "GET_AVATAR_PARTNER_FAIL"

//update avatar partner
export const UPDATE_AVATAR_PARTNER_REQUEST = "UPDATE_AVATAR_PARTNER_REQUEST"
export const UPDATE_AVATAR_PARTNER_SUCCESS = "UPDATE_AVATAR_PARTNER_SUCCESS"
export const UPDATE_AVATAR_PARTNER_FAIL = "UPDATE_AVATAR_PARTNER_FAIL"

//edit name partner
export const EDIT_NAME_PARTNER_REQUEST = "EDIT_NAME_PARTNER_REQUEST"
export const EDIT_NAME_PARTNER_SUCCESS = "EDIT_NAME_PARTNER_SUCCESS"
export const EDIT_NAME_PARTNER_FAIL = "EDIT_NAME_PARTNER_FAIL"

//get date info
export const GET_DATE_REQUEST = "GET_DATE_REQUEST"
export const GET_DATE_REQUEST_SUCCESS = "GET_DATE_REQUEST_SUCCESS"
export const GET_DATE_REQUEST_FAIL = "GET_DATE_REQUEST_FAIL"

//add date info
export const ADD_DATE_REQUEST = "ADD_DATE_REQUEST"
export const ADD_DATE_REQUEST_SUCCESS = "ADD_DATE_REQUEST_SUCCESS"
export const ADD_DATE_REQUEST_FAIL = "ADD_DATE_REQUEST_FAIL"

//edit date info
export const EDIT_DATE_REQUEST = "EDIT_DATE_REQUEST"
export const EDIT_DATE_REQUEST_SUCCESS = "EDIT_DATE_REQUEST_SUCCESS"
export const EDIT_DATE_REQUEST_FAIL = "EDIT_DATE_REQUEST_FAIL"

//get notification
export const GET_NOTIFICATION_REQUEST = "GET_NOTIFICATION_REQUEST"
export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS"
export const GET_NOTIFICATION_FAIL = "GET_NOTIFICATION_FAIL"

//create notificaiton
export const CREATE_NOTIFICATION_REQUEST = "CREATE_NOTIFICATION_REQUEST"
export const CREATE_NOTIFICATION_SUCCESS = "CREATE_NOTIFICATION_SUCCESS"
export const CREATE_NOTIFICATION_FAIL = "CREATE_NOTIFICATION_FAIL"

//active synccode
export const ACTIVED_SYNCCODE_REQUEST = "ACTIVED_SYNCCODE_REQUEST"
export const ACTIVED_SYNCCODE_SUCCESS = "ACTIVED_SYNCCODE_SUCCESS"
export const ACTIVED_SYNCCODE_FAIL = "ACTIVED_SYNCCODE_FAIL"

//active synccode
export const DENY_SYNCCODE_REQUEST = "DENY_SYNCCODE_REQUEST"
export const DENY_SYNCCODE_SUCCESS = "DENY_SYNCCODE_SUCCESS"
export const DENY_SYNCCODE_FAIL = "DENY_SYNCCODE_FAIL"

//cancel synccode
export const CANCEL_SYNCCODE_REQUEST = "CANCEL_SYNCCODE_REQUEST"
export const CANCEL_SYNCCODE_SUCCESS = "CANCEL_SYNCCODE_SUCCESS"
export const CANCEL_SYNCCODE_FAIL = "CANCEL_SYNCCODE_FAIL"