
//login user
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS"
export const LOGIN_REQUEST_FAIL = "LOGIN_REQUEST_FAIL"

//get user
export const GET_USERS_REQUEST = "GET_USERS_REQUEST"
export const GET_USERS_REQUEST_SUCCESS = "GET_USERS_REQUEST_SUCCESS"
export const GET_USERS_REQUEST_FAIL = "GET_USERS_REQUEST_FAIL"


